### ISSUE TITLE
Could not resolve module: org.openhab.binding.sonoff [24] - Unresolved requirement: Import-Package: javax.measure; version="[1.0.0,2.0.0)"

### ISSUE THREAD

**Issue by LeeNX** [delid4ve/openhab-3.x-sonoff#11]
Raspberry Pi OpenHAB 3.0.2 just upgraded to 3.1.0 and now getting the following error?
```
2021-07-12 11:53:56.425 [WARN ] [org.apache.felix.fileinstall        ] - Error while starting bundle: file:/usr/share/openhab/addons/org.openhab.binding.sonoff-3.1.0-SNAPSHOT_v2.4r2.jar
org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.sonoff [24]
  Unresolved requirement: Import-Package: javax.measure; version="[1.0.0,2.0.0)"

        at org.eclipse.osgi.container.Module.start(Module.java:463) ~[org.eclipse.osgi-3.16.200.jar:?]
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:440) ~[org.eclipse.osgi-3.16.200.jar:?]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1260) [bundleFile:3.6.8]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1233) [bundleFile:3.6.8]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.startAllBundles(DirectoryWatcher.java:1221) [bundleFile:3.6.8]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:515) [bundleFile:3.6.8]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365) [bundleFile:3.6.8]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316) [bundleFile:3.6.8]
```

**Comment by delid4ve** [comment]
You will need to use 3.0.3 jar version as javax.measure got changed (or im soon compiling 3.2.0 version.
